#!/usr/bin/python

# /cygdrive/c/Program\ Files/Python27/python.exe

# data-3.2CD

import argparse
from datetime import datetime
from dateutil import tz
import os
import random
import re
import socket
import string
import subprocess
import sys

DEBUG = False
# DEBUG = True


def submit():
    if DEBUG:
        import pdb
        pdb.set_trace()

    host = specHostname()

    # schedulerType is used in myparser
    if host == 'zagros':
        schedulerType = 'PBS'

    if host == 'seawulf':
        schedulerType = 'slurm'

    ( args, generatedOutputFilename ) = myparser(schedulerType)

    # Generate the stdout filename
    dst = tz.gettz('America/New_York')
    time = datetime.now(dst)
    if args.cfd:
        stdoutname = 'cfd'
    elif args.data:
        stdoutname = 'data'
    else:
        stdoutname = 'lpt'
    stdoutname += '.stdout.{:0>4d}{:0>2d}{:0>2d}.{:0>2d}{:0>2d}{:0>2d}' \
        .format(time.year, time.month, time.day, \
                time.hour, time.minute, time.second)
    print('stdout filename is {}'.format(stdoutname))


    # Setup executable names
    if host == 'zagros':
        CFD_PROG  = '/mnt/lustre/wayne/bin/VFS-Geophysics-3.2CD'
        DATA_PROG = '/mnt/lustre/wayne/bin/data-3.2CD'
        LPT_PROG  = '/mnt/lustre/wayne/bin/tracking'

    if host == 'seawulf':
        CFD_PROG  = '/gpfs/home/hseyyedzadeh/bin/VFS-Geophysics-3.1_mhk_login'
        DATA_PROG = '/gpfs/home/hseyyedzadeh/bin/data-3.1'
        LPT_PROG  = '/gpfs/home/hseyyedzadeh/bin/tracking'

    if not args.program:
        if args.cfd:
            args.program = CFD_PROG
        elif args.data:
            args.program = DATA_PROG
        else:
            args.program = LPT_PROG


    with open(args.output, 'w') as f:
        f.write('#!/bin/bash\n')
        f.write('\n')
        if schedulerType == 'PBS':
            f.write('#PBS -N {}\n'.format(args.jobname))
            f.write('#PBS -l nodes={}:ppn={}\n'.format(args.nodes, args.ppn))
            f.write('#PBS -l walltime={}\n'.format(args.time))
            # f.write('#PBS -o {}\n'.format(stdoutname))
            f.write('#PBS -m a\n')
            f.write('#PBS -k oe\n')
            f.write('#PBS -j oe\n')


            f.write('\n')
            f.write('cd "$PBS_O_WORKDIR"\n')
    
        if schedulerType == 'slurm':
            f.write('#SBATCH --job-name={}\n'.format(args.jobname))
            f.write('#SBATCH --nodes={}\n'.format(args.nodes))
            f.write('#SBATCH --ntasks={}\n'.format(args.ppn))
            f.write('#SBATCH --time={}\n'.format(args.time))
            f.write('#SBATCH -p {}\n'.format(args.queue))
            f.write('#SBATCH --output={}\n'.format(stdoutname))
    
        f.write('\n')
        if schedulerType == 'PBS':
            f.write('exec > {} 2>&1\n'.format(stdoutname))
        else:
            f.write('exec 2>&1\n')


        if schedulerType == 'slurm':
            f.write('\n')
            f.write('\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \n')
            f.write('echo \'job id:\' $SLURM_JOB_ID\n')
            f.write('echo \n')
            f.write('echo squeue -j $SLURM_JOB_ID\n')
            f.write('squeue -j $SLURM_JOB_ID\n')
            f.write('echo \n')

        f.write('\n')
        f.write('\n')
        f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
        f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
        f.write('echo \'>>>>>{}\'\n'.format(args.output))
        f.write('echo \n')
        f.write('cat {}\n'.format(args.output))
        f.write('echo \n')

        f.write('\n')
        f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
        f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
        f.write('echo \'>>>>> find . -type l | sort | xargs -r ls -l\'\n')
        f.write('echo \n')
        f.write('find . -type l | sort | xargs -r ls -l\n')
        f.write('echo \n')

        if args.cfd:
            f.write('\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \'>>>>>bcs.dat\'\n')
            f.write('echo \n')
            f.write('cat bcs.dat\n')
            f.write('echo \n')

            if args.rstart:
                f.write('\n')
                f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
                f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
                mod = -1
                if args.rstartmod:
                    mod = args.rstartmod
                setupRstart(f, mod)
                f.write('echo \n')

        if args.cfd:
            f.write('\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \'>>>>>control.dat\'\n')
            f.write('echo \n')
            f.write('cat control.dat\n')
            f.write('echo \n')

        if args.lpt:
            f.write('\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \'>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\'\n')
            f.write('echo \'>>>>>control.lpt.dat\'\n')
            f.write('echo \n')
            f.write('cat control.lpt.dat\n')
            f.write('echo \n')

        f.write('echo \'<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\'\n')
        f.write('echo \'<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\'\n')


        if (generatedOutputFilename):
            f.write('\n')
            f.write('\\rm {}\n'.format(args.output))

        if args.m:
            f.write('\n')
            f.write('echo\n')
            f.write('echo ">>> cpu info <<<"\n')
            f.write('echo\n')
            f.write('cat /proc/cpuinfo\n')
            f.write('echo\n')
            f.write('echo ">>> <<<"\n')
            f.write('echo\n')
            f.write('echo ">>> memory info <<<"\n')
            f.write('echo\n')
            f.write('cat /proc/meminfo\n')
            f.write('echo\n')
            f.write('echo ">>> <<<"\n')
            f.write('echo\n')
            f.write('\n')

        f.write('\n')
        f.write('START_TIME=`date`\n')
        f.write('echo\n')
        f.write('echo "Start time: $START_TIME"\n')
    
        progargs = ' '
        if args.cfd:
            if args.tio:
                progargs += ' -tio {}'.format(args.tio)
            if args.totalsteps:
                progargs += ' -totalsteps {}'.format(args.totalsteps)

        if args.data:
            progargs = ' -tis {} -ts {} -tie {}'.format(args.tis, args.ts, args.tie)
            if args.ftley < 0.99e30:
                progargs += ' -ftley {}'.format(args.ftley)

        f.write('\n')
        if schedulerType == 'PBS':
            f.write('module load acml gnu openmpi\n')
            f.write('\n')
            if args.data:
                # f.write('mpirun --bind-to core {} -avg {}{}\n'.format(args.program, args.avg, progargs))
                exeargs = ''
                if args.nexe > 0:
                    exeargs = '-n {}'.format(args.nexe)
                cmdbuff = 'mpirun {} -n 1 --bind-to core {}'.format(exeargs, args.program,)
                if args.avg:
                    cmdbuff += ' -avg {}'.format(args.avg)
                if args.averaging:
                    cmdbuff += ' -averaging {}'.format(args.averaging)
                cmdbuff += '{}\n'.format(progargs)
                f.write(cmdbuff)
            elif args.lpt:
                f.write('mpirun -n 1 --bind-to core {}{}\n'.format(args.program, progargs))
            else:
                f.write('mpirun --bind-to core {}{}\n'.format(args.program, progargs))
    
        if schedulerType == 'slurm':
            #if args.script is None:
            f.write(' module load gcc/6.5.0 \n')
            f.write(' module load blas/gcc/64/3.8.0 \n')
            f.write(' module load lapack/gcc/64/3.8.0 \n')
            f.write(' module load mvapich2/gcc/64/2.2rc1 \n')
            f.write(' module load shared \n')
            f.write('\n')

            if args.data:
                # f.write('mpirun {} -avg {}{}\n'.format(args.program, args.avg, progargs))
                exeargs = ''
                if args.nexe > 0:
                    exeargs = '-np {}'.format(args.nexe)
                cmdbuff = 'mpirun -n 1 {} {}'.format(exeargs, args.program,)
                exeargs = ''
                if args.avg:
                    cmdbuff += ' -avg {}'.format(args.avg)
                if args.averaging:
                    cmdbuff += ' -averaging {}'.format(args.averaging)
                cmdbuff += '{}\n'.format(progargs)
                f.write(cmdbuff)
            elif args.lpt:
                f.write('mpirun -n 1 {}{}\n'.format(args.program, progargs))
            else:
                f.write('mpirun {}{}\n'.format(args.program, progargs))

        f.write('\n')
        f.write('echo\n')
        f.write('echo "Start time: $START_TIME"\n')
        f.write('echo "End time:   `date`"\n')


    # Submit the job.
    if host == 'zagros':
        cmdLine = [ 'qsub' ]
        if args.after:
            cmdLine += [ '-W depend=afterany:' + args.after ]
        cmdLine += [ args.output ]
    else:
        # qSubmit = 'sbatch'
        cmdLine = [ 'sbatch' ]
        if args.after:
            cmdLine += [ '-d', 'afterany:' + args.after ]
        cmdLine += [ args.output ]
 
    if not args.nq:
        plotsp = subprocess.Popen(cmdLine, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        (stdoutdata, stderrdata) = plotsp.communicate()
        print(stdoutdata.decode("utf-8"))

    else:
        print(' '.join(cmdLine))

# When -rstart is specified, find the most recent results from output
# files and update the control file with the rstart time step.
def setupRstart(f, mod):
    f.write('\n')
    f.write('echo\n')
    f.write('# Find the most recent results from output files and\n')
    f.write('# update the control file with the rstart time step.\n')
    f.write('# export LAST_TS=`ls vfield[0-9][0-9][0-9][0-9][0-9][0-9]_0.dat | sort | tail -n 1 \\\n')
    f.write('#                | sed \'s/vfield\\([0-9][0-9][0-9][0-9][0-9][0-9]\\)_0.dat/\\1/\'` || exit 1\n')
    f.write('export LAST_TS=`lastTimeStep.py {}`\n'.format(mod))
    f.write('sed "/^-rstart/ s/^.\\+/-rstart $LAST_TS/" < control.dat > control.dat.tmp || exit 1\n')
    f.write('\\rm control.dat || exit 1\n')
    f.write('mv control.dat.tmp control.dat || exit 1\n')
    f.write('echo Last time step: $LAST_TS\n')

# My parse parameters.  I mostly want the same parameters, but for data runs, I want some specifically for it.
# -c --cfd:  Submit a cfd job
# -d --data: Submit a job to generate results data
# -l --lpt:  Submit a job for Lagrangian Particle Tracking

def myparser(schedulerType):
    mainparser = argparse.ArgumentParser()

    # Command line options used to modify parameter list.
    hbool = False
    databool = False
    if len(sys.argv) >= 2:
        for i in range(1, len(sys.argv)):
            if sys.argv[i] == '-h':
                hbool = True
            if sys.argv[i] == '-d' or sys.argv[i] == '--data':
                databool = True

    # You can only do a cfd, lpt or data job
    exclgroup = mainparser.add_mutually_exclusive_group()
    exclgroup.add_argument('-c', '--cfd', help='Submit a cfd job', action='store_true', default=False)
    exclgroup.add_argument('-d', '--data', help='Submit a job to generate results data', action='store_true', default=False)
    exclgroup.add_argument('-l', '--lpt', help='Submit a lpt job', action='store_true', default=False)

    # These are the common options.
    mainparser.add_argument('--cpu', help='Show cpu information', action='store_true', default=False)

    mainparser.add_argument('-j', '--jobname', help='Name for this job', required=True)
    mainparser.add_argument('-N', '--nodes', help='number of nodes for job', default=1, type=int)
    mainparser.add_argument('-n', '--ppn', help='number of processors per node', default=1, type=int)
    mainparser.add_argument('-o', '--output', help='Queue submission filename', default=None)
    mainparser.add_argument('-t', '--time', help='elapsed time needed', default='1:00:00')
    mainparser.add_argument('-m', '--m', action='store_true', help='Show machine hardward.', default=False)

    mainparser.add_argument('--mem', help='Show memory information', action='store_true', default=False)

    mainparser.add_argument('-nq', '--nq', action='store_true', help='Don\'t queue job', default=False)
    mainparser.add_argument('-after', help='Wait for specified job to finish.', default=None)

    # Not needed for zagros PBS, needed for slurm.  I don't want it to show up in the help for
    # zagros but I still want it in so I can use the same command line from seawulf.
    if schedulerType == 'slurm' or not hbool:
        mainparser.add_argument('-q', '--queue', help='computer queue', default='short-28core')

    # Override the program to run
    mainparser.add_argument('-x', '--program', help='program path')

    # Options for cfd run only. They will only show up if -h or --cfd are in the command line.
    if hbool or not databool:
        mainparser.add_argument('-rstart', action='store_true', help='Set restart timestep based on current last timestep (for --cfd only)', default=False)
        mainparser.add_argument('-rstartmod', help='restart with last time step modulo rstartmod.', default=-1, type=int)
        mainparser.add_argument('-tio', help='Offset between times steps (for --cfd only)', default=None, type=int)
        mainparser.add_argument('-totalsteps', help='Stop at this time step (for --cfd only)', default=None, type=int)


    # These are the options for --data only.  They will only show up if -h or --data are in the command line.
    if hbool or databool:
        mainparser.add_argument('-avg', '--avg', help='Specify variable averaging (for --data only)', default=None, type=int)
        mainparser.add_argument('-averaging', '--averaging', help='Other averaging options (for --data only)', default=None, type=int)
        mainparser.add_argument('-tis', '--tis', help='Beginning timestep (for --data only)', required=True, type=int)
        mainparser.add_argument('-ts',  '--ts',  help='Step size between beginning and ending timestep (for --data only)', default=None, type=int)
        mainparser.add_argument('-tie', '--tie', help='Ending timestep (for --data only)', default=None, type=int)
        mainparser.add_argument('-ftley', '--ftley', help='Output files for FTLE processing (for --data only)', default=1.0e30, type=float)
        mainparser.add_argument('-nexe',  '--nexe',  help='Number of processors for the executable to use (for --data only)', default=0, type=int)

    arg = mainparser.parse_args()
    if not arg.cfd ^ (arg.data | arg.lpt):
        arg.cfd=True

    # print arg

    if arg.data:
        if not arg.tie:
            arg.tie = arg.tis
        if not arg.ts:
            arg.ts = 1

    generatedOutputFilename = False
    if not arg.output:
        generatedOutputFilename = True
        arg.output = 'submit.tmp.' + randomString() + '.sh'

    if not databool and arg.rstartmod > 0:
        arg.rstart = True

    return ( arg, generatedOutputFilename )



def randomString():
    avail = string.ascii_letters + string.digits
    return ''.join(random.choice(avail) for i in range(8))



# Is this hostname supported?
def specHostname():
    host = socket.getfqdn()
    # print('hostname is {}'.format(host))

    if host == 'zagros':
        return 'zagros'

#     if re.search('\.cm\.cluster$', host):
    if   re.match('login[12]', host) \
      or re.match('milan[12]', host):
        return 'seawulf'

    print('This host, {}, is not yet supported.')
    exit(1)
        


if __name__ == '__main__':
    submit()
